version: '3'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - monitor-net
    deploy:
      mode: global
      restart_policy:
          condition: on-failure

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
  # Tests the current internet connection speed
  # once per hour and writes the results into an
  # InfluxDB instance
  speedtest:
    image: robinmanuelthiel/speedtest:0.1.1
    container_name: speedtest
    restart: always
    depends_on:
      - pg
    environment:
      - LOOP=true
      - LOOP_DELAY=3600 # Once per hour
      - DB_SAVE=true
      - DB_HOST=http://postgresql:8080
      - DB_NAME=speedtest
      - DB_USERNAME=admin
      - DB_PASSWORD=123456a.

  pg:
    image: postgres
    restart: always
    container_name: postgresql
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: 123456a.
      POSTGRES_USER: admin
      POSTGRES_DB: speedtest
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
  
  noip:
    image: coppit/no-ip
    container_name: noip
    restart: always
    environment:
      - USERNAME=gregoiredemoulin2@gmail.com
      - PASSWORD=EpR%$kg3q2
      - DOMAINS=yberamoss.ddns.net
      - INTERVAL=3

volumes:
  grafana:
  pgdata:
  prometheus-data: