---
- name: Upgrade
  become: true
  apt:
    upgrade: full

- name: Install packages for apt add repository
  become: true
  apt:
    name: "{{ packagesdep }}"
    state: latest
    update_cache: true
    force_apt_get: true
  vars:
    packagesdep:
      - snap