
---
- name: generate SSH key "{{ssh_key_filename}}"
  user:
    name: "{{ansible_user}}"
    generate_ssh_key: true
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ssh_key_filename}}
    ssh_key_passphrase: "{{ssh_passphrase}}"
    force: no
  vars:
    ssh_key_filename: id_rsa_myproject
  vars_prompt:
    - name: "ssh_passphrase"
      prompt: "Enter the passphrase for the SSH key"

- name: Copy ssh keys
  authorized_key: 
    user: "{{ansible_user}}"
    state: present
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true