---
- name: download install script
  become: true
  command: curl -fsSL https://get.docker.com -o get-docker.sh

- name: execute install script
  become: true
  command: sh get-docker.sh

- name: Add "{{ansible_user}}" in the docker group
  become: true
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: true
