---
- name: Install microk8s
  become: true
  snap:
    name: microk8s
    classic: true

- name: join group
  become: true
  user:
    name: "{{ansible_user}}"
    groups: microk8s
    append: true

- name: change ownership of /home/{{ansible_user}}/.kube
  file:
    path: ~/.kube
    owner: "{{ansible_user}}"
    state: directory
    recurse: true