---
- name: Upgrade
  become: true
  apt:
    upgrade: full

- name: Install packages for apt add repository
  become: true
  apt:
    name: "{{ packagesdep }}"
    state: latest
    update_cache: true
    force_apt_get: true
  vars:
    packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - man
      - libffi-dev
      - libssl-dev
      - python3-dev
      - python3
      - python3-pip