---
- name: Creating user yberamos
  user:
    name: yberamos
    shell: /bin/bash
    groups: sudo, docker
    append: yes    
    update_password: always
    password: "{{ newpassword|password_hash('sha512') }}"